### PR TITLE
merged breadcrumbs from old branch

### PR DESCRIPTION
**Pull request by mbreese**
breadcrumbs can be toggled on/off by a checkbox
the most recent bot to traverse a box is shown
if the bots share a box, it is shown in gray.

This should address your earlier issues.

### CODE REVIEW

**Comment by mbreese** [comment]
This is a new branch which contains the same pull request that I issued earlier. I added a few other features that you may or may not want, so I wanted to split things into different branches so I could do separate pull requests.

**Comment by jennylin** [comment]
Looks like if the bot share a box and player 2 went second it correctly shows grey but if player 1 went second he still stomps his teal Xs over it. But I think this is good enough for me to merge. If you'd like to fix those issues I'd be happy to merge in the fix when it's done.

**Comment by mbreese** [comment]
Well, it's hard to figure out what the best strategy is for this…

Originally, it was 'whoever is first' gets to mark the tile.
This time, it's 'whoever was last' gets to mark the tile, and only
when both players are on the tile at the same time is the tile marked
with a grey X.

However, the other option is to make it a combination where each
player marks their own squares, but if they land on a tile that the
other player previously marked, then the tile is switched to a grey X.

The basic logic is:
player1 pos = x1,y1
player2 pos = x2,y2

history[x1][y1] |= 1
history[x2][y2] |= 2

1 = teal X, 2 = red X, 3 = grey X

## Do you think that would be better?

Marcus Breese

On Fri, May 25, 2012 at 3:06 PM, Jennifer Lin
reply@reply.github.com
wrote:

**Comment by jennylin** [comment]
Ah, I thought that was what you meant to do. I think that would be clear enough for tracing purposes. I also assume the user is stepping through and watching their bot as well as they are going through so they should have some memory of what happened and who went into that area first. I personally like that option better. =)

**Comment by mbreese** [comment]
So do I. I guess that I just got confused with your first message. I'll send a pull request later tonight. 

And thanks for running such a fun contest. 

Marcus

**Pull request merged**
